# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_view_compress.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(736, 418)
        Form.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_4 = QtGui.QWidget(Form)
        self.widget_4.setMinimumSize(QtCore.QSize(100, 20))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 8, 0, 1, 3)
        self.le_desiredsp = QtGui.QLineEdit(self.widget_4)
        self.le_desiredsp.setText(_fromUtf8(""))
        self.le_desiredsp.setAlignment(QtCore.Qt.AlignCenter)
        self.le_desiredsp.setObjectName(_fromUtf8("le_desiredsp"))
        self.gridLayout_3.addWidget(self.le_desiredsp, 4, 0, 1, 3)
        self.label = QtGui.QLabel(self.widget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.le_sp = QtGui.QLineEdit(self.widget_4)
        self.le_sp.setMinimumSize(QtCore.QSize(75, 35))
        self.le_sp.setText(_fromUtf8(""))
        self.le_sp.setAlignment(QtCore.Qt.AlignCenter)
        self.le_sp.setObjectName(_fromUtf8("le_sp"))
        self.gridLayout_3.addWidget(self.le_sp, 1, 0, 1, 3)
        self.le_sp_step = QtGui.QLineEdit(self.widget_4)
        self.le_sp_step.setMinimumSize(QtCore.QSize(75, 0))
        self.le_sp_step.setAlignment(QtCore.Qt.AlignCenter)
        self.le_sp_step.setReadOnly(False)
        self.le_sp_step.setObjectName(_fromUtf8("le_sp_step"))
        self.gridLayout_3.addWidget(self.le_sp_step, 6, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.widget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 9, 0, 1, 1)
        self.widget_5 = QtGui.QWidget(self.widget_4)
        self.widget_5.setMinimumSize(QtCore.QSize(75, 0))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_spdw = QtGui.QPushButton(self.widget_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/a_dw.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_spdw.setIcon(icon)
        self.btn_spdw.setIconSize(QtCore.QSize(24, 24))
        self.btn_spdw.setObjectName(_fromUtf8("btn_spdw"))
        self.horizontalLayout.addWidget(self.btn_spdw)
        self.btn_spup = QtGui.QPushButton(self.widget_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/a_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_spup.setIcon(icon1)
        self.btn_spup.setIconSize(QtCore.QSize(24, 24))
        self.btn_spup.setObjectName(_fromUtf8("btn_spup"))
        self.horizontalLayout.addWidget(self.btn_spup)
        self.gridLayout_3.addWidget(self.widget_5, 7, 0, 1, 3)
        self.gridLayout.addWidget(self.widget_4, 0, 0, 3, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        self.widget_3 = QtGui.QWidget(Form)
        self.widget_3.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 1, 1, 1)
        self.btn_slrtdw = QtGui.QPushButton(self.widget_3)
        self.btn_slrtdw.setIcon(icon1)
        self.btn_slrtdw.setIconSize(QtCore.QSize(24, 24))
        self.btn_slrtdw.setObjectName(_fromUtf8("btn_slrtdw"))
        self.gridLayout_2.addWidget(self.btn_slrtdw, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_slrt = QtGui.QLineEdit(self.widget_3)
        self.le_slrt.setMinimumSize(QtCore.QSize(75, 20))
        self.le_slrt.setAlignment(QtCore.Qt.AlignCenter)
        self.le_slrt.setObjectName(_fromUtf8("le_slrt"))
        self.gridLayout_2.addWidget(self.le_slrt, 1, 0, 1, 2)
        self.btn_slrtup = QtGui.QPushButton(self.widget_3)
        self.btn_slrtup.setIcon(icon)
        self.btn_slrtup.setIconSize(QtCore.QSize(24, 24))
        self.btn_slrtup.setObjectName(_fromUtf8("btn_slrtup"))
        self.gridLayout_2.addWidget(self.btn_slrtup, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_slrt_step = QtGui.QLineEdit(self.widget_3)
        self.le_slrt_step.setMinimumSize(QtCore.QSize(75, 20))
        self.le_slrt_step.setAlignment(QtCore.Qt.AlignCenter)
        self.le_slrt_step.setReadOnly(False)
        self.le_slrt_step.setObjectName(_fromUtf8("le_slrt_step"))
        self.gridLayout_2.addWidget(self.le_slrt_step, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 3, 1)
        self.widget = QtGui.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(200, 300))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.le_control_state = QtGui.QLineEdit(self.widget)
        self.le_control_state.setMinimumSize(QtCore.QSize(75, 35))
        self.le_control_state.setAlignment(QtCore.Qt.AlignCenter)
        self.le_control_state.setObjectName(_fromUtf8("le_control_state"))
        self.gridLayout_4.addWidget(self.le_control_state, 1, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btn_control_start = QtGui.QPushButton(self.widget_2)
        self.btn_control_start.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_control_start.setObjectName(_fromUtf8("btn_control_start"))
        self.verticalLayout.addWidget(self.btn_control_start)
        self.btn_control_stop = QtGui.QPushButton(self.widget_2)
        self.btn_control_stop.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_control_stop.setObjectName(_fromUtf8("btn_control_stop"))
        self.verticalLayout.addWidget(self.btn_control_stop)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_4.addWidget(self.widget_2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 3, 3, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.btn_spdw, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionSPDw)
        QtCore.QObject.connect(self.btn_spup, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionSPUp)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionApplySetPoint)
        QtCore.QObject.connect(self.le_desiredsp, QtCore.SIGNAL(_fromUtf8("returnPressed()")), Form.actionApplySetPoint)
        QtCore.QObject.connect(self.btn_slrtup, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionSlrtDw)
        QtCore.QObject.connect(self.btn_slrtdw, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionSlrtUp)
        QtCore.QObject.connect(self.btn_control_start, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionStartControl)
        QtCore.QObject.connect(self.btn_control_stop, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.actionStopControl)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_sp, self.le_slrt)
        Form.setTabOrder(self.le_slrt, self.le_control_state)
        Form.setTabOrder(self.le_control_state, self.le_desiredsp)
        Form.setTabOrder(self.le_desiredsp, self.le_sp_step)
        Form.setTabOrder(self.le_sp_step, self.btn_spdw)
        Form.setTabOrder(self.btn_spdw, self.btn_spup)
        Form.setTabOrder(self.btn_spup, self.pushButton)
        Form.setTabOrder(self.pushButton, self.le_slrt_step)
        Form.setTabOrder(self.le_slrt_step, self.btn_slrtup)
        Form.setTabOrder(self.btn_slrtup, self.btn_slrtdw)
        Form.setTabOrder(self.btn_slrtdw, self.btn_control_start)
        Form.setTabOrder(self.btn_control_start, self.btn_control_stop)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_2.setText(_translate("Form", "Step", None))
        self.pushButton.setToolTip(_translate("Form", "Press to apply the desired value", None))
        self.pushButton.setText(_translate("Form", "Apply", None))
        self.le_desiredsp.setToolTip(_translate("Form", "Desired pressure controller set point", None))
        self.label.setText(_translate("Form", "Current Set Point, bar", None))
        self.le_sp.setToolTip(_translate("Form", "Current pressure controller set point", None))
        self.le_sp_step.setToolTip(_translate("Form", "Setpoint step", None))
        self.label_6.setText(_translate("Form", "Desired Set Point, bar", None))
        self.btn_spdw.setToolTip(_translate("Form", "Decrease a desired setpoint (press Apply to implement)", None))
        self.btn_spdw.setText(_translate("Form", "Down", None))
        self.btn_spup.setToolTip(_translate("Form", "Increase a desired setpoint (press Apply to implement)", None))
        self.btn_spup.setText(_translate("Form", "Up", None))
        self.btn_slrtdw.setToolTip(_translate("Form", "Increase slew rate (applied immediately)", None))
        self.btn_slrtdw.setText(_translate("Form", "Up", None))
        self.label_4.setText(_translate("Form", "Slewrate, bar", None))
        self.le_slrt.setToolTip(_translate("Form", "Current slew rate", None))
        self.btn_slrtup.setToolTip(_translate("Form", "Decrease slew rate (applied immediately)", None))
        self.btn_slrtup.setText(_translate("Form", "Down", None))
        self.label_3.setText(_translate("Form", "Step", None))
        self.le_slrt_step.setToolTip(_translate("Form", "Slewrate step", None))
        self.label_5.setText(_translate("Form", "Press. Controller State", None))
        self.le_control_state.setToolTip(_translate("Form", "Pressure controller state", None))
        self.btn_control_start.setToolTip(_translate("Form", "Starts operation of the pressure controller", None))
        self.btn_control_start.setText(_translate("Form", "Start", None))
        self.btn_control_stop.setToolTip(_translate("Form", "Stops operation of the pressure controller", None))
        self.btn_control_stop.setText(_translate("Form", "Stop", None))

import app_rc
