__author__ = 'Konstantin Glazyrin'

PROFILE_DIR = "PROFILE_DIR"
PROFILE_PRIORITY = "PROFILE_PRIORITY"

PROFILE_TANGO_ADDRESS = "PROFILE_TANGO_ADDRESS"

PROFILE_NAME = "PROFILE_NAME"
PROFILE_START = "PROFILE_START"

PROFILE_HTML = "PROFILE_HTML"
PROFILE_ATTRLOOP = "PROFILE_ATTRLOOP"

ADDRESS, ATTR, DESC = "ADDRESS", "ATTR", "DESC"

PROFILE_DELAY = "PROFILE_DELAY"

DATA = "DATA"

FORMAT = "FORMAT"

DATASTR = "DATASTR"

WDGT = "WDGT"

PROFILE_CONTROLLERS = "PROFILE_CONTROLLERS"

NICK, CMD, SEPARATOR, ARGS = "NICK", "CMD", "SEPARATOR", "ARGS"